# .gitlab-ci.yml — инструкция для робота GitLab CI

stages:
  - test                  # этапы конвейера (у нас пока один — "test")

playwright-tests:                                      # имя задачи (job) — любое
  stage: test                                          # эта задача относится к этапу "test"
  image: mcr.microsoft.com/playwright:v1.60.0-jammy    # готовая среда, где браузеры и Playwright 1.60.0 уже стоят
  script:
    - npm ci                # установить зависимости строго по package-lock.json
    - npx playwright test   # запустить тесты
